apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: backend
  name: backend
spec:
  containers:
  - image: nginx
    name: backend
    livenessProbe:
     httpGet:
       path: /
       port: 80
     initialDelaySeconds: 10
     periodSeconds: 10
     successThreshold: 1
     timeoutSeconds: 4
    readinessProbe:
     httpGet:
       path: /
       port: 80
     initialDelaySeconds: 5
     periodSeconds: 5
     successThreshold: 1
     timeoutSeconds: 2

