apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-container
  name: multi-container
spec:
  containers:
  - image: nginx
    name: nginx
  - image: alpine
    name: alpine
    args: ['sleep','15000']  

